const funds=[
{type:'musica',name:'Ibermúsicas · Circulación',amount:'USD 10.000',status:'Cerró · 01.10.2026',fit:'Prioridad alta para una gira con invitaciones',text:'Admite profesionales de países elegibles. Requiere cartas de anfitriones y registro en el catálogo. Las bases 2026 excluyen gastos sueltos de gasolina, peajes y viáticos: no asumir que cubre el uso de la casa rodante.',url:'https://www.ibermusicas.org/wp-content/uploads/2026/05/1-Ayuda-a-la-circulacion-de-profesionales-de-la-musica-2026.pdf'},
{type:'musica',name:'Ibermúsicas · Residencias',amount:'Según bases',status:'Cerró · 01.10.2026',fit:'Condicionada a residencia y elegibilidad',text:'La edición 2026 requiere al menos tres semanas y una invitación. Argentina no figura en la lista habilitada de esta línea; confirmar residencia certificada elegible. No trasladar requisitos de circulación a residencias.',url:'https://www.ibermusicas.org/wp-content/uploads/2026/06/3-Ayuda-a-artistas-e-investigadores-para-residencias-2026-ok.pdf'},
{type:'memoria',name:'Fundación Cultural Latin GRAMMY',amount:'USD 5.000',status:'Cerró · 27.08.2026',fit:'Para un proyecto específico de investigación o archivo',text:'Apoya investigación y preservación de música latina. El recorrido debe traducirse en un tema delimitado, metodología y resultados; no es una ayuda general para giras.',url:'https://www.latingrammyculturalfoundation.org/news/latin-grammy-cultural-foundation-opens-applications-for-its-2026-latin-music-research-and-preservation-grant-program/'},
{type:'institucional',name:'UNESCO · Diversidad Cultural',amount:'USD 100.000',status:'Cerró · 06.05.2026',fit:'Vía institucional de mediano plazo',text:'Proyectos de 12 a 24 meses, postulados por instituciones públicas u ONG elegibles. Deben generar cambios estructurales en el sector cultural. Julio podría participar en un proyecto compartido; no postular una gira individual.',url:'https://www.unesco.org/creativity/en/ifcd/apply'},
{type:'institucional',name:'UNESCO · Programa de Participación',amount:'USD 26–38 mil',status:'Cerró · 27.02.2026',fit:'Requiere canal institucional autorizado',text:'Los topes varían según alcance nacional, subregional o regional. Las solicitudes pasan por Estados o por ONG en asociación oficial con UNESCO. No es una ventanilla individual para artistas.',url:'https://www.unesco.org/en/member-states-portal/participation-programme'},
{type:'musica',name:'Prince Claus · Seed Award',amount:'EUR 5.000',status:'Convocatoria 2026 cerrada',fit:'Prioridad baja hasta verificar trayectoria',text:'Dirigido a artistas con uno a cinco años de práctica profesional y procedencia, residencia y trabajo en países elegibles. La prensa menciona cinco años de profesionalismo en febrero de 2026: confirmar fechas antes de considerar una futura edición.',url:'https://princeclausfund.nl/awards-and-programmes/seed-award/2026-call-for-applications'}];
function renderFunds(){let type=document.querySelector('#fundFilter').value;document.querySelector('#funds').innerHTML=funds.filter(f=>type==='all'||f.type===type).map(f=>`<article class="fund"><div><span class="tag">${f.status}</span><h2>${f.name}</h2><strong>${f.fit}</strong><p>${f.text}</p><a href="${f.url}" target="_blank" rel="noopener">Consultar fuente oficial</a></div><div class="amount"><small>TOPE O REFERENCIA 2026</small>${f.amount}</div></article>`).join('')}
function navigate(){const id=location.hash.slice(1)||'presentacion';const valid=['presentacion','proyecto','financiamiento','archivo'].includes(id)?id:'presentacion';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==valid);document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.view===valid);if(a.dataset.view===valid)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});window.scrollTo(0,0)}window.addEventListener('hashchange',navigate);document.querySelector('#fundFilter').addEventListener('change',renderFunds);renderFunds();navigate();
